version: '3.8'

services:
  n8n:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=adminpass
      - DB_TYPE=sqlite
      - TZ=America/Sao_Paulo
    volumes:
      - n8n_data:/home/node/.n8n
    restart: always

volumes:
  n8n_data:
